
import type { Metadata } from 'next'
import Header from '@/components/header/Header'
import { Inter } from 'next/font/google'
import AuthSession from '@/components/AuthSession';
import '../scss/reset.modules.scss';
import Footer from '@/components/footer/Footer';
import { ReduxProvider } from '@/redux/ReduxProvider';
import { headers } from 'next/headers'
import { Session } from 'next-auth'
import { Suspense } from 'react'
import Loading from './loading';

const inter = Inter({ subsets: ['latin'], fallback:['system-ui', 'arial'], display: 'swap', })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch(`https://babanshop.vercel.app/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getSession(headers().get('cookie') ?? '');
  return (
    <html lang="ko">
      <body className={inter.className}>
          <AuthSession session={session}>
            <ReduxProvider>
              {/* <Suspense fallback={<Loading/>}> */}
                <Header/>
                <main style={{ minHeight: 'calc(100vh - 9rem)' }}>
                {children}
                </main>
                <Footer/>
              {/* </Suspense> */}
            </ReduxProvider>
          </AuthSession>
      </body>
    </html>
  )
}
